import { Outlet, useLocation } from 'react-router-dom';
import { Navbar } from './Navbar';
import { motion, AnimatePresence } from 'motion/react';
import { useState, useRef, useEffect } from 'react';
import { Play, Pause, SkipForward, Settings, Volume2, X, Music } from 'lucide-react';
import { get } from 'idb-keyval';

const DEFAULT_TRACKS = [
  { id: 1, title: "搞笑音乐·听完笑到打鸣", artist: "《小组摸鱼之歌》", url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3" },
  { id: 2, title: "深夜肝代码专属", artist: "无情干饭机器", url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3" },
  { id: 3, title: "赛博朋克 2077 Vibe", artist: "夜之城节奏", url: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3" }
];

export function Layout() {
  const location = useLocation();
  
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTrackIndex, setCurrentTrackIndex] = useState(0);
  const [showSettings, setShowSettings] = useState(false);
  const [volume, setVolume] = useState(0.5);
  const [tracks, setTracks] = useState(DEFAULT_TRACKS);

  const audioRef = useRef<HTMLAudioElement>(null);

  // Scroll to top on route change
  useEffect(() => {
    window.scrollTo(0, 0);
  }, [location.pathname]);

  // Load saved custom tracks & volume
  useEffect(() => {
    const loadTracks = async () => {
      try {
        const savedTracks = localStorage.getItem('team_music_tracks');
        if (savedTracks) {
          const parsedTracks = JSON.parse(savedTracks);
          
          // Hydrate local references from object URLs generated by idb-keyval blob extraction if necessary
          for (let track of parsedTracks) {
            if (track.fileId) {
               try {
                  const blob = await get(track.fileId);
                  if (blob) {
                    track.url = URL.createObjectURL(blob);
                  }
               } catch(ex) {
                  console.error('Failed to reconstruct blob url', ex);
               }
            }
          }
          setTracks(parsedTracks);
        }
      } catch (e) {
        console.error(e);
      }
    };
    
    // Initial load
    loadTracks();
    
    const savedVolume = localStorage.getItem('team_music_volume');
    if (savedVolume) {
      setVolume(parseFloat(savedVolume));
    }

    window.addEventListener('sync_music_tracks', loadTracks);
    return () => window.removeEventListener('sync_music_tracks', loadTracks);
  }, []);

  // Update audio volume
  useEffect(() => {
    if (audioRef.current) {
      audioRef.current.volume = volume;
    }
  }, [volume]);

  const currentTrack = tracks[currentTrackIndex] || tracks[0];

  useEffect(() => {
    if (audioRef.current) {
      if (isPlaying) {
        const playPromise = audioRef.current.play();
        if (playPromise !== undefined) {
          playPromise.catch(e => {
            if (e.name !== 'AbortError') {
              console.error("Audio playback error:", e);
              setIsPlaying(false);
            }
          });
        }
      } else {
        audioRef.current.pause();
      }
    }
  }, [isPlaying, currentTrackIndex, currentTrack?.url]);

  const handlePlayPause = () => {
    setIsPlaying(!isPlaying);
  };

  const handleNext = () => {
    const nextIndex = (currentTrackIndex + 1) % tracks.length;
    setCurrentTrackIndex(nextIndex);
    setIsPlaying(true);
  };

  const handleAudioEnded = () => {
    handleNext();
  };

  return (
    <div className="min-h-screen flex flex-col relative px-safe">
      {/* Subtle background effects */}
      <div className="fixed inset-0 pointer-events-none -z-10 bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-neon-green/10 via-transparent to-transparent flex" />
      
      <Navbar />
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 pt-24 pb-32">
        <AnimatePresence mode="wait">
          <motion.div
            key={location.pathname}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -20 }}
            transition={{ duration: 0.3 }}
          >
            <Outlet />
          </motion.div>
        </AnimatePresence>
      </main>

      <audio 
        ref={audioRef} 
        src={currentTrack?.url} 
        onEnded={handleAudioEnded}
      />

      {/* Music Player Bar */}
      <motion.div 
        initial={{ y: 100 }}
        animate={{ y: 0 }}
        transition={{ delay: 1 }}
        className="fixed bottom-6 left-1/2 -translate-x-1/2 glass-card px-4 py-3 border-2 border-black dark:border-white shadow-[4px_4px_0_var(--color-ink)] flex items-center gap-4 z-[60] bg-white dark:bg-[#111] text-black dark:text-white w-[90%] max-w-md"
      >
        <div className={`w-10 h-10 rounded-full bg-accent-color/20 border-2 border-black dark:border-white flex items-center justify-center shrink-0 ${isPlaying ? 'animate-[spin_4s_linear_infinite]' : ''}`}>
          <Music className="w-5 h-5 text-accent-color" />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-sm font-bold truncate">{currentTrack?.title}</p>
          <p className="text-xs opacity-60 truncate">{currentTrack?.artist}</p>
        </div>
        <div className="flex gap-1 shrink-0">
          <button onClick={handlePlayPause} className="p-2 border-2 border-transparent hover:border-black dark:hover:border-white transition-colors">
            {isPlaying ? <Pause className="w-5 h-5" /> : <Play className="w-5 h-5" />}
          </button>
          <button onClick={handleNext} className="p-2 border-2 border-transparent hover:border-black dark:hover:border-white transition-colors">
            <SkipForward className="w-5 h-5" />
          </button>
          <button onClick={() => setShowSettings(!showSettings)} className={`p-2 border-2 transition-colors ${showSettings ? 'border-neon-pink text-neon-pink' : 'border-transparent hover:border-black dark:hover:border-white'}`}>
            <Settings className="w-5 h-5" />
          </button>
        </div>
      </motion.div>

      {/* Music Settings Drawer / Modal */}
      <AnimatePresence>
        {showSettings && (
          <motion.div 
            initial={{ opacity: 0, y: 50, scale: 0.95 }}
            animate={{ opacity: 1, y: 0, scale: 1 }}
            exit={{ opacity: 0, y: 50, scale: 0.95 }}
            className="fixed bottom-24 left-1/2 -translate-x-1/2 w-[90%] max-w-md glass-card border-4 border-black dark:border-white shadow-[8px_8px_0_var(--color-ink)] p-4 sm:p-6 z-[50] bg-white dark:bg-[#111] text-black dark:text-white max-h-[70vh] flex flex-col"
          >
            <div className="flex justify-between items-center mb-6 shrink-0 border-b-2 border-black/10 dark:border-white/10 pb-4">
              <h3 className="font-black text-xl uppercase flex items-center gap-2 tracking-tighter">
                <Music className="w-6 h-6 text-neon-pink" /> 音源控制面板
              </h3>
              <button onClick={() => setShowSettings(false)} className="hover:text-neon-pink p-1"><X className="w-5 h-5" /></button>
            </div>

            <div className="overflow-y-auto pr-2 scrollbar-thin scrollbar-thumb-black dark:scrollbar-thumb-white scrollbar-track-transparent flex-1 space-y-6">
              {/* Volume */}
              <div>
                <label className="flex items-center gap-2 text-xs font-bold uppercase mb-2">
                  <Volume2 className="w-4 h-4" /> 输出功率 (音量)
                </label>
                <input 
                  type="range" 
                  min="0" max="1" step="0.01" 
                  value={volume}
                  onChange={(e) => {
                    const v = parseFloat(e.target.value);
                    setVolume(v);
                    localStorage.setItem('team_music_volume', v.toString());
                  }}
                  className="w-full accent-neon-pink h-2 bg-black/10 dark:bg-white/10 appearance-none outline-none"
                />
              </div>

              {/* Track List */}
              <div>
                <label className="block text-xs font-bold uppercase mb-2">可用音轨</label>
                <div className="space-y-2">
                  {tracks.map((track, idx) => (
                    <div 
                      key={track.id} 
                      onClick={() => { setCurrentTrackIndex(idx); setIsPlaying(true); }}
                      className={`flex justify-between items-center p-2 border-2 transition-colors ${idx === currentTrackIndex ? 'border-accent-color bg-accent-color/10' : 'border-black/20 dark:border-white/20 hover:border-black dark:hover:border-white cursor-pointer'}`}
                    >
                      <div className="flex-1 min-w-0">
                        <div className="font-bold text-sm truncate">{track.title}</div>
                        <div className="text-[10px] opacity-60 font-mono truncate">{track.artist}</div>
                      </div>
                      <div className="flex items-center gap-2 pl-2">
                        {idx === currentTrackIndex && isPlaying && <div className="w-2 h-2 bg-accent-color rounded-full animate-bounce" />}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
